global using AlchemyLub.Blueprint.Application.Services;
global using AlchemyLub.Blueprint.Application.Services.Abstractions;
global using AlchemyLub.Blueprint.Domain;
global using AlchemyLub.Blueprint.Domain.Abstractions;
global using AlchemyLub.Blueprint.SharedKernel.Enums;
global using AlchemyLub.Blueprint.SharedKernel.Requests;
global using AlchemyLub.Blueprint.SharedKernel.Responses;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.DependencyInjection;
