namespace AlchemyLub.Blueprint.Generator.RawConstantFiles;

internal sealed class RawAttributes
{
    internal const string DecoratorAttributes =
"""
// <auto-generated/>
namespace DecoratorGenerator.Attributes
{
    /// <summary>
    /// Attribute that marks the decorated method
    /// </summary>
    [AttributeUsage(AttributeTargets.Method, Inherited = false)]
    public sealed class DecorateAttribute<T> : System.Attribute
    {
    }
}
""";
}
