namespace AlchemyLub.Blueprint.Generator.Templates;

internal static class ClassComponents
{
    internal const string ExtensionClassHead =
"""
// <auto-generated />
#nullable enable
using System;

public static class DecoratorsExtensions_generated
{
    public static IServiceCollection AddDecorators(this IServiceCollection services, IConfiguration configuration)
    {
""";

    internal const string ExtensionClassBasement =
"""
        return services;
    }
}
""";
}
