global using System.Reflection;
global using FloralHub.Blueprint.App.Extensions;
global using FloralHub.Blueprint.Application.Services.Abstractions;
global using FloralHub.Blueprint.Domain.Abstractions;
global using FloralHub.Blueprint.Endpoints.Controllers;
global using FloralHub.Blueprint.Infrastructure.Services;
global using FloralHub.Blueprint.SharedKernel.Enums;
global using FluentAssertions;
global using NetArchTest.Rules;
