global using System.Collections.Frozen;
global using System.ComponentModel;
global using System.Diagnostics.CodeAnalysis;
global using System.Reflection;
global using AlchemyLub.Blueprint.Application.Services.Abstractions;
global using AlchemyLub.Blueprint.ArchTests.Enums;
global using AlchemyLub.Blueprint.ArchTests.Extensions;
global using AlchemyLub.Blueprint.ArchTests.Results;
global using AlchemyLub.Blueprint.ArchTests.Services;
global using AlchemyLub.Blueprint.Clients.Abstractions;
global using AlchemyLub.Blueprint.Domain;
global using AlchemyLub.Blueprint.Endpoints.Controllers;
global using AlchemyLub.Blueprint.Endpoints.Requests;
global using AlchemyLub.Blueprint.Infrastructure.Services;
global using FluentAssertions;
global using Microsoft.AspNetCore.Mvc;
global using NetArchTest.Rules;
global using static AlchemyLub.Blueprint.ArchTests.Constants;
global using ClientEntityResponse = AlchemyLub.Blueprint.Clients.Responses.EntityResponse;
global using ClientEntityRequest = AlchemyLub.Blueprint.Clients.Requests.EntityRequest;
