namespace AlchemyLab.Blueprint.MinimalControllers.Generator.Constants;

/// <summary>
/// Константы для шаблонов кода
/// </summary>
public static class Templates
{
    /// <summary>
    /// Пространство имен по умолчанию для генерируемого кода
    /// </summary>
    public const string DefaultNamespace = "MinimalControllers";

    /// <summary>
    /// Название класса по умолчанию для методов расширения
    /// </summary>
    public const string DefaultExtensionClassName = "MinimalControllersExtensions";

    /// <summary>
    /// Название метода по умолчанию для маппинга всех контроллеров
    /// </summary>
    public const string DefaultMapAllMethodName = "MapGeneratedControllers";

    /// <summary>
    /// Шаблон для строки генерации кода (автоматически сгенерировано)
    /// </summary>
    public const string AutoGeneratedComment = "// <auto-generated />";

    /// <summary>
    /// Шаблон для строки включения nullable контекста
    /// </summary>
    public const string NullableEnableComment = "#nullable enable";

    /// <summary>
    /// Шаблон имени параметра приложения
    /// </summary>
    public const string AppParameterName = "app";

    /// <summary>
    /// Шаблон имени параметра группы маршрутов
    /// </summary>
    public const string GroupParameterName = "group";

    /// <summary>
    /// Суффикс имени контроллера
    /// </summary>
    public const string ControllerSuffix = "Controller";

    /// <summary>
    /// Суффикс имени метода для маппинга API контроллера
    /// </summary>
    public const string MapApiSuffix = "Api";

    /// <summary>
    /// Стандартный отступ в пробелах
    /// </summary>
    public const int StandardIndentSize = 4;
}
